name: khabroom_admin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+10

environment:
  sdk: ">=3.12.1"
  flutter: ">=3.44.1"

#  flutter clean && flutter build apk --target-platform android-arm64,android-arm --release
#  flutter clean && flutter build web --release

#  flutter pub global activate rename
#  flutter pub global run rename setBundleId --value com.scimed.app
#  flutter pub global run rename setAppName --value "SCI-MED"
#  flutter pub run flutter_launcher_icons:main
dependencies:
  flutter:
    sdk: flutter

  u:
    path: U_flutter

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "lib/assets/images/logo_launcher.png"
  min_sdk_android: 21
  ios:
    generate: true
    image_path: "lib/assets/images/logo_launcher.png"
    background_color: "#000000"
    theme_color: "#hexcode"
  web:
    generate: true
    image_path: "lib/assets/images/logo_launcher.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "lib/assets/images/logo_launcher.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "lib/assets/images/logo_launcher.png"

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
    - lib/assets/images/
    - lib/assets/icons/

flutter_intl:
  enabled: true